# 문제 NP12-0001

다음과 3차원 배열 np1 을 만들고, axis 에 따른 합을 구하는 프로그램의 결과를 그리시오.


```python
np2 = np1.sum(axis=0)
np3 = np1.sum(axis=1)
np4 = np1.sum(axis=2)
```



In [15]:
import numpy as np
np1 = np.arange(0, 24).reshape(2, 3, 4)
print(np1)

np2 = np1.sum(axis=0)
print("\naxis=0 블록끼리 행 기준")
print(np2)

np3 = np1.sum(axis=1)
print("\naxis=1 블록 내 행끼리")
print(np3)

np4 = np1.sum(axis=2)
print("\naxis=2 블록 내 행의 열끼리")
print(np4)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

axis=0 블록끼리 행 기준
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

axis=1 블록 내 행끼리
[[12 15 18 21]
 [48 51 54 57]]

axis=2 블록 내 행의 열끼리
[[ 6 22 38]
 [54 70 86]]


# 문제 NP12-0002

임의값으로 3x6 배열을 만들고, 최대 최소값을 출력하는 프로그램을 작성하시오.

- 조건
    - np.random.random() 함수 사용
    - **소숫점2째 자리까지 표현**
    - **행별** 최소, 최대값을 출력한다. (아래 표 참조)
    - 반복문 사용x
    - 리스트 사용 x

In [42]:
import numpy as np
np1 = np.round(np.random.random((1, 3, 6)), 2)
print(np1)

# axis=2 : 블록 내 행의 열끼리
print('max:', np.max(np1, axis=2))
print('min:', np.min(np1, axis=2))

[[[0.39 0.01 0.95 0.38 0.87 0.41]
  [0.23 0.27 0.59 0.51 0.47 0.62]
  [0.05 0.01 0.07 0.08 0.92 0.8 ]]]
max: [[0.95 0.62 0.92]]
min: [[0.01 0.23 0.01]]


# 문제 NP12-0003

임의값으로 3x6 배열을 만들고, 최대 최소값을 출력하는 프로그램을 작성하시오.

- 조건
    - np.random.random() 함수 사용
    - **소숫점2째 자리까지 표현**
    - **열별** 최소, 최대값을 출력한다. (아래 표 참조)
    - 반복문 사용x
    - 리스트 사용 x

In [5]:
import numpy as np

np1 = np.random.random((1,3,6))
np1_rounded = np.round(np1, 2)
print(np1_rounded)

# axis=1: 블록 내의 행끼리
print('max:', np.max(np1_rounded, axis=1))
print('min:', np.min(np1_rounded, axis=1))

[[[0.6  0.88 0.21 0.24 0.01 0.23]
  [0.31 0.52 0.21 0.32 0.52 0.09]
  [0.62 0.16 0.95 0.88 0.61 0.1 ]]]
max: [[0.62 0.88 0.95 0.88 0.61 0.23]]
min: [[0.31 0.16 0.21 0.24 0.01 0.09]]


###문제 NP14-0000
다음 프로그램의 결과를 작성하시오.


```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[7, 8, 9],[10, 11, 12]])
```

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.array([[1, 2, 3],[4, 5, 6]])
d = np.array([[7, 8, 9],[10, 11, 12]])

In [161]:
print("a", a)
print("b", b)
print("\n열 병합")
print(np.hstack([a, b]))

a [1 2 3]
b [4 5 6]

열 병합
[1 2 3 4 5 6]


In [89]:
print("c")
print(c)
print("d")
print(d)

print("\n같은 행 기준으로 열 병합")
print(np.hstack([c,d]))

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

같은 행 기준으로 열 병합
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [58]:
import numpy as np
a = np.array([1, 2, 3])
d = np.array([[7, 8, 9],[10, 11, 12]])
np.hstack([a,d]) # 차원이 다르므로 에러

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [162]:
print("a", a)
print("b", b)
print("\nb의 마지막 원소 제거 후 열 병합")
print(np.hstack([a,b[:-1]]))

a [1 2 3]
b [4 5 6]

b의 마지막 원소 제거 후 열 병합
[1 2 3 4 5]


In [91]:
print("c")
print(c)
print("d")
print(d)

print("\nd의 첫번째 원소 제거 후 열 병합")
print(np.hstack([c,d[:,1:]]))

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

d의 첫번째 원소 제거 후 열 병합
[[ 1  2  3  8  9]
 [ 4  5  6 11 12]]


In [93]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a", a)
print("b", b)
print("\n1차원 배열시 한 줄로 이어붙임")
print(np.r_[a, b])

a [1 2 3]
b [4 5 6]

1차원 배열시 한 줄로 이어붙임
[1 2 3 4 5 6]


In [96]:
print("a", a)
print("b", b)
print("\n행 추가로 이어붙여, 2차원 배열로 만듬")
print(np.r_[[a], [b]])

a [1 2 3]
b [4 5 6]

행 추가로 이어붙여, 2차원 배열로 만듬
[[1 2 3]
 [4 5 6]]


In [98]:
print("a", a)
print("c")
print(c)
print("\n행 추가로 2차원 배열로 만듦")
print(np.r_[[a], c])

a [1 2 3]
c
[[1 2 3]
 [4 5 6]]

행 추가로 2차원 배열로 만듦
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [99]:
print("c")
print(c)
print("d")
print(d)
print("\n행 추가로 2차원 배열로 만듦")
print(np.r_[c, d])

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

행 추가로 2차원 배열로 만듦
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [100]:
print("c")
print(c)
print("d")
print(d)
print("\n열 추가로 배열 병합")
print(np.c_[c, d])

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

열 추가로 배열 병합
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [107]:
print("a", a)
print("b", b)
print("\n1차원 배열 병합")
print(np.concatenate((a,b), axis=0))

a [1 2 3]
b [4 5 6]

1차원 배열 병합
[1 2 3 4 5 6]


In [112]:
print(np.r_[0:5:0.5])
print(np.c_[0:5:0.5])

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[0. ]
 [0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]
 [3. ]
 [3.5]
 [4. ]
 [4.5]]


In [118]:
print("a", a)
print("b", b)
print("\n행병합")
print(np.vstack([a,b]))

a [1 2 3]
b [4 5 6]

행병합
[[1 2 3]
 [4 5 6]]


In [119]:
print("c")
print(c)
print("d")
print(d)
print("\n행병합")
print(np.vstack([c,d]))

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

행병합
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [123]:
print("a", a)
print("c")
print(c)
print("\n행 병합")
print(np.vstack([a,c]))

a [1 2 3]
c
[[1 2 3]
 [4 5 6]]

행 병합
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [126]:
print("a", a)
print("b", b)
print("\n행 추가하여 배열 병합")
print(np.r_[[a], [b]])

a [1 2 3]
b [4 5 6]

행 추가하여 배열 병합
[[1 2 3]
 [4 5 6]]


In [129]:
print("a", a)
print("c")
print(c)
print("\n행병합")
print(np.r_[[a], c])

a [1 2 3]
c
[[1 2 3]
 [4 5 6]]

행병합
[[1 2 3]
 [1 2 3]
 [4 5 6]]


In [133]:
print("c")
print(c)
print("d")
print(d)
print("\n행병합")
print(np.r_[c, d])

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

행병합
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [163]:
print("a", a)
print("b", b)
print("\n행기준 병합")
print(np.concatenate((a,b), axis=0))

print("\n1차원 배열에서는 axis=1이 존재하지 않으므로")
# np.concatenate((a,b), axis=1)

print("\n행기준 병합")
print(np.concatenate(([a],[b]), axis=0))

print("\n열기준 병합")
print(np.concatenate(([a],[b]), axis=1))

a [1 2 3]
b [4 5 6]

행기준 병합
[1 2 3 4 5 6]

1차원 배열에서는 axis=1이 존재하지 않으므로

행기준 병합
[[1 2 3]
 [4 5 6]]

열기준 병합
[[1 2 3 4 5 6]]


In [143]:
print("a", a)
print("b", b)
print("\n열병합")
print(np.column_stack([a,b]))

a [1 2 3]
b [4 5 6]

열병합
[[1 4]
 [2 5]
 [3 6]]


In [145]:
print("c")
print(c)
print("d")
print(d)
print("\n열병합")
print(np.column_stack([c,d]))

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

열병합
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [155]:
print("a", a)
print("b", b)
print("\n열병합")
print(np.c_[a, b])

print()
print("c")
print(c)
print("d")
print(d)
print("\n열병합")
print(np.c_[c, d])

a [1 2 3]
b [4 5 6]

열병합
[[1 4]
 [2 5]
 [3 6]]

c
[[1 2 3]
 [4 5 6]]
d
[[ 7  8  9]
 [10 11 12]]

열병합
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [164]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a_reshaped = a.reshape(3, 1)
b_reshaped = b.reshape(3, 1)
print("1차원 배열을 axis=1으로 할 수 없으므로, 2차원 배열로 만들어준 후 열병합")
print(np.concatenate((a_reshaped, b_reshaped), axis=1))

1차원 배열을 axis=1으로 할 수 없으므로, 2차원 배열로 만들어준 후 열병합
[[1 4]
 [2 5]
 [3 6]]
